"""make changes to the tables

Revision ID: 056490e78571
Revises: 23df65cd1d52
Create Date: 2019-11-23 17:08:31.458910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056490e78571'
down_revision = '23df65cd1d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('date_posted', sa.DateTime(timezone=250), nullable=False),
    sa.Column('pitches_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pitches_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('date', sa.DateTime(timezone=250), nullable=True))
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'time')
    op.add_column('users', sa.Column('password_hash', sa.String(length=250), nullable=True))
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_hash')
    op.add_column('pitches', sa.Column('time', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'date')
    op.drop_table('comment_vote')
    # ### end Alembic commands ###
