"""Initial Migration

Revision ID: 44da79f3f0e2
Revises: 77bf3e4acb62
Create Date: 2019-11-23 14:56:30.546844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44da79f3f0e2'
down_revision = '77bf3e4acb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###
