"""make changes to the tables

Revision ID: 47931553b228
Revises: 056490e78571
Create Date: 2019-11-23 20:10:59.363500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47931553b228'
down_revision = '056490e78571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_pitches_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'pitches_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitches_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_pitches_id_fkey', 'users', 'pitches', ['pitches_id'], ['id'])
    # ### end Alembic commands ###
